logging:
  level: INFO
  loggers:
    org.raado: DEBUG

server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 8888
  adminConnectors:
    - type: http
      port: 8881
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

defaultName: aman

userCollectionName: raado-users

transactionCollectionName: raado-transactions

staticResourceCollectionName: raado-resource

swagger:
  resourcePackage: org.raado.resources
  title: Raado
  description: Raado Resources

mongoConfig:
  mongohost: 127.0.0.1
  mongodbName: inventory

cacheConfig:
  concurrency: 32
  expiryInMinutes: 90
  maxElements: 1024
  refreshInMinutes: 60