package org.raado.exceptions;

public enum ErrorCode {
    PHONE_NUMBER_ALREADY_EXISTS,
    USERID_OR_PASSWORD_IS_INCORRECT,
    PASSWORD_IS_INCORRECT,
    INTERNAL_ERROR,
    PERMISSIONS_ACCESS_ISSUE
}
